# mplayer -input keylist

P PAUSE
SPACE PAUSE

O OSD
K OSD_SHOW_PROGRESSION
A SWITCH_AUDIO
a SWITCH_AUDIO
T SUB_SELECT
t SUB_SELECT
M MUTE
m MUTE
#MOUSE_BTN0 PAUSE

MOUSE_BTN0_DBL VO_FULLSCREEN
MOUSE_BTN1 OSD
MOUSE_BTN2 OSD_SHOW_PROGRESSION

ENTER PAUSE
KP_ENTER PAUSE

#NO ALT? 
ESC VO_FULLSCREEN 0
CTRL-ENTER VO_FULLSCREEN
CTRL-f VO_FULLSCREEN
CTRL-F VO_FULLSCREEN
f VO_FULLSCREEN
F VO_FULLSCREEN

#-------------
#PGUP VOLUME +1
#PGDWN VOLUME -1
#HOME VOLUME +1
#END VOLUME -1
#INS VOLUME +1
#DEL VOLUME -1
#--------------

l GET_TIME_POS
L GET_TIME_LENGTH