#!/bin/sh
#(c) Copyright BK 2012, GPL3
#shared-mime-info pkg has assigned initrd.gz mime-type application/initramfs-gz (by me).
#Click on initrd.gz/xz in a file manager, this script will run (see ${HOME}/Choices/MIME-types/application_initramfs-gz).
#note: script not internationalized, as this is a developer's tool.
# cli/gui

if [ "$DISPLAY" ] ; then
	DIALOG='Xdialog --cr-wrap'
else
	DIALOG='dialog --colors --cr-wrap'
fi

zhelp() {
	script=${0##*/} ; echo "
Usage:

       $script -x|-c <initrd.gz/xz>
          -x: extract
          -c: compress"
	exit
}

if [ "`gzip --help 2>&1 | grep '\-k'`" ] ; then
	#gzip 1.5 doesn't support -k ...
	GZIP=gzip
	GUNZIP=gunzip
elif [ "`busybox gzip --help 2>&1 | grep '\-k'`" ] ; then
	GZIP='busybox gzip'
	GUNZIP='busybox gunzip'
fi

#find out compression type...
function compr_func() {
	comp="$(file -b "$1")"
	case "$comp" in
		gz*|GZ*) UNCOMPREXE=${GUNZIP} ; EXT=gz ; COMPREXE=${GZIP} ;;
		xz*|XZ*) UNCOMPREXE=unxz   ; EXT=xz ; COMPREXE='xz --check=crc32 --lzma2' ;;
		*cpio*|*CPIO*) CPIO=1 ;; #fd64
		*) echo "Unsupported compression/format for initrd."
			exit 1 ;;
	esac
}

#find out partition filesystem a file is located in
function FILE_FS_IS_OK() {
	[ $FILE_FS_IS_OK ] && return $FILE_FS_IS_OK
	local MOUNTPOINT="$(stat -c '%m' "$@")"
	local FS="$(mount | grep " $MOUNTPOINT " | cut -f 5 -d ' ')"
	case $FS in
		ext*|rootfs) FILE_FS_IS_OK=0 ;;
		*) FILE_FS_IS_OK=1 ;;
	esac
	return $FILE_FS_IS_OK
}

##################################################
# CLI (to extract and recompress in the same dir)
##################################################

function initrd_proc() { #<extract|compress> [-home] <initrd.gz/xz>

	OPTION=$1
	shift
	[ "$1" = "-home" ] && { TOHOME=1; shift; }

	INFILE="$@"
	case $INFILE in
		*'initrd-expanded')
			INITRD_DIR=1
			if ! [ -e "$INFILE" ] ; then
				echo "ERROR: file does not exist: $INFILE"
				exit 1
			fi
			INFILE=$(dirname $INFILE)/initrd.gz
			UNCOMPREXE=${GUNZIP} EXT=gz COMPREXE=${GZIP}
			;;
		*)
			if ! [ -f "$INFILE" ] ; then
				echo "ERROR: file does not exist: $INFILE"
				exit 1
			fi
			;;
	esac
	DIR="`dirname "$INFILE"`"
	FILE_NAME=${INFILE##*/}

	CURDIRX=$DIR
	if ! FILE_FS_IS_OK "$DIR" ; then
		TOHOME=1
	fi
	[ $TOHOME ] && DIR=${HOME}

	cd "$DIR"

	## now proceed
	if [ ! "$INITRD_DIR" -o "$CPIO" != "" ] ; then
		if [ $TOHOME ] ; then
			cp -fv "$INFILE" ${HOME}
		fi
		if ! [ -f initrd -o -f initrd.gz -o -f initrd.xz ] ; then
			echo "initrd.gz/xz not found in $DIR"
			exit 1
		fi
		if ! compr_func ${FILE_NAME} ; then
			echo "ERROR getting compression type for ${FILE_NAME}" >&2
			return 1
		fi
	fi

	if [ "$OPTION" = "extract" ] ; then
		echo "Expanding at $DIR"
		if [ "$CPIO" = "" ] ; then
			if [ "initrd.${EXT}" != "${FILE_NAME}" ] ; then
				cp -f "${FILE_NAME}" initrd.${EXT}
			fi
			#-f and -k are options in gunzip, and unxz
			zout=$($UNCOMPREXE -f -k initrd.${EXT} 2>&1)
			if [ $? -ne 0 ] ; then
				echo -e "${comp}\n${zout}" >&2
				rm -f initrd.${EXT}
				return 5 #error extracting
			fi
		fi
		mkdir -p initrd-expanded
		cd initrd-expanded
		cat ../initrd | cpio -i -d -m
		rm -f ../initrd
		cd ..
		[ "initrd.${EXT}" != "${FILE_NAME}" ] && rm -f initrd.${EXT}
		[ "$TOHOME" ] && rm -f ${HOME}/${FILE_NAME}
		return 0
	else #compress
		echo "Creating $FILE_NAME from $DIR"
		if ! [ -d initrd-expanded ] ; then
			echo "'initrd-expanded' not found in $DIR"
			exit 1
		fi
		cd initrd-expanded
		find . | cpio -o -H newc > ../initrd
		cd ..
		${COMPREXE} -f initrd
		[ "initrd.${EXT}" != "${FILE_NAME}" ] && mv -f initrd.${EXT} "${FILE_NAME}"
		[ "$TOHOME" -a "$HOME" != "$CURDIRX" ] && mv -fv ${FILE_NAME} "$CURDIRX"
		return 0
	fi
}

#================================================

case $1 in
	-x) shift ; initrd_proc extract "$@" ; exit $? ;;
	-c) shift ; initrd_proc compress "$@" ; exit $? ;;
	-h|-help|--help) zhelp ; exit $? ;;
esac

[ $DISPLAY ] || zhelp

##################################################
#					GUI
##################################################

zfile="$1"
[ ! -f "$zfile" ] && exit 1
zfile="$(realpath "$zfile")"
DIRX="`dirname "$zfile"`"
BASEFILE="`basename "$zfile"`"

case "${BASEFILE}" in
	*initrd|*"initrd.gz"|*"initrd.xz") ok=1 ;;
	*) exit 1 ;;
esac

cd ${HOME}
[ -f initrd ] && rm -f initrd
[ -f /tmp/${BASEFILE} ] && rm -f /tmp/${BASEFILE}
[ "$zfile" = "${HOME}/${BASEFILE}" ] && cp -f ${HOME}/${BASEFILE} /tmp/

if [ -d "${HOME}/initrd-expanded" ] ; then
	ex1="An ${BASEFILE} is already expanded at ${HOME}/initrd-expanded."
	msgx="Is this correct, do you want to use ${HOME}/initrd-expanded to update ${zfile}?"
	expanded_home=1
fi

if [ -d "$DIRX/initrd-expanded" ] ;then
	if FILE_FS_IS_OK "$DIRX/initrd-expanded" ; then
		ex2="An ${BASEFILE} is already expanded at $DIRX/initrd-expanded."
		msgx="Is this correct, do you want to use $DIRX/initrd-expanded to update ${zfile}?"
		expanded_dir=1
	fi
fi

if [ "$expanded_home" -a "$expanded_dir" ] ; then
	msgx="Please choose one of the above dirs to update ${BASEFILE}"
fi

EXP_DIR=$DIRX/initrd-expanded

if [ "$expanded_home" -o "$expanded_dir" ] ; then ### COMPRESS ###

	if [ "$expanded_home" -a "$expanded_dir" ] ; then
		#initrd-expanded is in both ${HOME} and $DIRX
		${DIALOG} \
		--title "${BASEFILE}: expand?" --extra-button \
		--yes-label "${HOME}" \
		--extra-label "$DIRX" \
		--no-label "Cancel" \
		--yesno "$ex1 $ex2 $msgx" 20 60
		retval=$?
		case $retval in
			0) toHOME="-home" ; EXP_DIR=${HOME}/initrd-expanded;; #"${HOME}"
			3) EXP_DIR=$DIRX/initrd-expanded ;; #"$DIRX"
			*) exit ;; #"Cancel"
		esac
	else
		#initrd-expanded is in ${HOME} OR $DIRX
		if [ "$DISPLAY" ] ; then
			/usr/lib/gtkdialog/box_yesno --yes-first \
				"${BASEFILE}: update?" "$ex1" "$ex2" "$msgx"
		else
			${DIALOG} --title "${BASEFILE}: update?" \
				--yesno "$ex1 $ex2 $msgx" 0 0
		fi
		[ $? -ne 0 ] && exit
		if [ "$expanded_home" ] ; then
			toHOME="-home"
			EXP_DIR=${HOME}/initrd-expanded
		fi
	fi

	initrd_proc compress $toHOME "$zfile"
	if [ "$DISPLAY" ] ; then
		/usr/lib/gtkdialog/box_ok "${BASEFILE}: success" complete "File ${zfile} has been updated with the contents of ${EXP_DIR}."
	else
		${DIALOG} --title "${BASEFILE}: success" --msgbox "File ${zfile} has been updated with the contents of ${EXP_DIR}." 0 0
	fi
	[ $toHOME ] || exit
	if [ "$DISPLAY" ] ; then
		/usr/lib/gtkdialog/box_yesno --yes-first \
		"${BASEFILE}: finished" "Do you want to delete ${HOME}/initrd-expanded?" "If in doubt, please choose Yes"
	else
		${DIALOG} --title "${BASEFILE}: finished" --yesno "Do you want to delete ${HOME}/initrd-expanded? If in doubt, please choose Yes" 0 0
	fi
	
	if [ $? -eq 0 ] ; then
		rm -rf ${HOME}/initrd-expanded
	fi
  
else ### EXPAND ###

	if FILE_FS_IS_OK "$DIRX" ; then
		${DIALOG} \
		--title "${BASEFILE}: expand?" \
		--yes-label "Expand at ${HOME}" \
		--extra-button --extra-label "Expand at Current dir" \
		--no-label "Cancel" \
		--yesno "Current dir:\n ${DIRX}\n\nDo you want to open up ${BASEFILE}, and optionally edit it?\n\n" 0 0
		retval=$?
		case $retval in
			0) toHOME="-home" ; EXP_DIR=${HOME}/initrd-expanded;; #"expand at ${HOME}"
			3) EXP_DIR=$DIRX/initrd-expanded ;; #"Expand at ${BASEFILE} dir"
			*) exit ;; #"Cancel"
		esac
	else
		msg="Do you want to open up ${BASEFILE}, and optionally edit it?\n\n"
		${DIALOG} --title "${BASEFILE}: expand?" --yes-label "Expand at ${HOME}" --no-label "Cancel" --yesno "$msg" 0 0
		[ $? -ne 0 ] && exit
		if [ "$expanded_home" ] ; then
			toHOME="-home"
			EXP_DIR=${HOME}/initrd-expanded
		fi
	fi

	initrd_proc extract $toHOME "$zfile"
	if [ $? -eq 5 ] ; then
		if [ "$DISPLAY" ] ; then
			exec /usr/lib/gtkdialog/box_ok "ERROR" error "error extracting initrd.${EXT}" "${zout}"
		else
			exec ${DIALOG} --title "ERROR" --msgbox "error extracting initrd.${EXT}\n\n${comp}\n\n${zout}" 0 0
		fi
	fi
	if [ "$DISPLAY" ] ; then
		/usr/lib/gtkdialog/box_ok "${BASEFILE}: expanded" complete "${BASEFILE}: expanded" "File ${BASEFILE} has been expanded at <b>${EXP_DIR}</b>. You may edit the contents if you wish." "<b>Afterward, if you click on ${zfile} again</b>, it will be updated with the contents of ${EXP_DIR}."
	else
		${DIALOG} --title "${BASEFILE}: expanded" --msgbox "File ${BASEFILE} has been expanded at \Zb${EXP_DIR}\ZB. You may edit the contents if you wish. \Zb\Z1\n\nAfterward, if you click on ${zfile} again\Zn\ZB, it will be updated with the contents of ${EXP_DIR}." 0 0
	fi
	if [ "$DISPLAY" ] && [ $toHOME ] ; then
		defaultfilemanager ${EXP_DIR}
	fi

fi

if [ -f /tmp/${BASEFILE} ] ; then
	rm -f /tmp/${BASEFILE}
fi

### END ###
