#!/bin/bash
#Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#a gui to provide choices for "events" -- things that occur at a systems level,
#usually hardware related.

#set -x

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505

export TEXTDOMAIN=eventmanager
export OUTPUT_CHARSET=UTF-8

SHOWMODE=$1 #v405 optional to modify gui.

. /etc/rc.d/PUPSTATE
. /etc/DISTRO_SPECS
. /etc/rc.d/MODULESCONFIG

[ -f /etc/eventmanager ] && . /etc/eventmanager
[ ! $RAMSAVEINTERVAL ] && RAMSAVEINTERVAL=30
[ "$ASKTOSAVE" != "true" -a "$ASKTOSAVE" != "false" ] && ASKTOSAVE="false"
[ "$HOTPLUGNOISY" != "true" -a "$HOTPLUGNOISY" != "false" ] && HOTPLUGNOISY="false"
[ "$PM13_TRAYICON" != "true" -a "$PM13_TRAYICON" != "false" ] && PM13_TRAYICON="true"
[ ! $POWERTIMEOUT ] && POWERTIMEOUT=0 #w007 0=never.

#w007 as have a optional cutdown gui, make sure these are all preset...
NEWRAMSAVEINTERVAL=$RAMSAVEINTERVAL
NEWHOTPLUGNOISY="$HOTPLUGNOISY"
NEWPOWERTIMEOUT=$POWERTIMEOUT
NEWPM13_TRAYICON="$PM13_TRAYICON"

#disable RAM save interval and floppy icon if logical
case $PUPMODE in 13) SENSITIVE_RAMSAVE="true";; *) SENSITIVE_RAMSAVE="false";; esac

#===============================================================

PAGE_NR=0
[ "$SHOWMODE" = "pm13" ] && PAGE_NR=1

auto_launch_chkbox='
            <checkbox>
              <label>'$(gettext "Auto-launch 'handler' when media plugged in")'</label>
              <default>'${HOTPLUGNOISY}'</default>
              <variable>NEWHOTPLUGNOISY</variable>
            </checkbox>'

#===============================================================

export PLinux_Event_Manager='
<window title="'$(gettext 'PLinux Event Manager')'" icon-name="gtk-execute">
<vbox space-expand="true" space-fill="true">
  <notebook tab-pos="2" page="'$PAGE_NR'" labels="'$(gettext 'Save Session')'">
    <vbox margin="8">
    <frame '$(gettext 'Periodic save from RAM')'>
      <vbox space-expand="true" space-fill="true">
        '"`/usr/lib/gtkdialog/xml_info scale PLinux_save.svg 60 "$(gettext "If a pupsave is loaded and you are booting from a usb flash drive or with the boot param pmedia=usbflash, you should be in PUPMODE 13. Currently running in PUPMODE=")${PUPMODE}. " "
$(gettext "If it is  13, then PLinux is doing everything in RAM -- this is done in the case of Flash memory to make it last longer. There should be a 'save' icon on the desktop, optionally a save can occur at shutdown. You can also specify a periodic save here.")" " "`"'
        <vbox space-expand="false" space-fill="false">
          <hbox sensitive="'${SENSITIVE_RAMSAVE}'">
            <text space-expand="false" space-fill="false">
              <label>"'$(gettext 'Save interval (0=never)')'  "</label>
            </text>
            <entry max_length="4" width-request="40" sensitive="'${SENSITIVE_RAMSAVE}'" space-expand="false" space-fill="false">
              <default>'${RAMSAVEINTERVAL}'</default>
              <variable>NEWRAMSAVEINTERVAL</variable>
            </entry>
            <text><label>"'$(gettext 'minutes')' "</label></text>
          </hbox>
         
          <vbox sensitive="'${SENSITIVE_RAMSAVE}'">
            <hbox homogeneous="true" sensitive="'${SENSITIVE_RAMSAVE}'">
              <checkbox>
                <default>'${ASKTOSAVE}'</default>
                <variable>NEWASKTOSAVE</variable>
                <label>"'$(gettext 'Ask at shutdown whether to save session or not.
(if unticked, session will be saved automatically)
(if save interval > 0, session will be saved automatically')'"</label>
              </checkbox>
            </hbox>
            <hbox homogeneous="true" sensitive="'${SENSITIVE_RAMSAVE}'">
              <checkbox>
                <default>'${PM13_TRAYICON}'</default>
                <variable>NEWPM13_TRAYICON</variable>
                <label>"'$(gettext 'Show Tray Icon')'"</label>
              </checkbox>
            </hbox>
            <hbox homogeneous="true" sensitive="'${SENSITIVE_RAMSAVE}'">
              <button space-expand="false" space-fill="false">
                <label>'$(gettext "Save RAM to pupsave NOW")'</label>
                '"`/usr/lib/gtkdialog/xml_button-icon floppy`"'
                <action>save2flash >/dev/null</action>
              </button>
            </hbox>
          </vbox>
        
        </vbox>
      </vbox>
    </frame>
    </vbox>
    
  </notebook>
  <hbox space-expand="false" space-fill="false">
    '${auto_launch_chkbox}'
    <text space-expand="true" space-fill="true"><label>""</label></text>
    <button space-expand="false" space-fill="false">
      <label>'$(gettext "Cancel")'</label>
      '"`/usr/lib/gtkdialog/xml_button-icon cancel`"'
      <action>exit:Cancel</action>
    </button>
    <button space-expand="false" space-fill="false">
      <label>'$(gettext "Ok")'</label>
      '"`/usr/lib/gtkdialog/xml_button-icon ok`"'
      <action>exit:OK</action>
    </button>    
  </hbox>
</vbox>
</window>'

. /usr/lib/gtkdialog/xml_info gtk #build bg_pixmap for gtk-theme
RETSTRING="`gtkdialog -p PLinux_Event_Manager`"
[ $? -ne 0 ] && exit

eval "$RETSTRING"
#echo "$RETSTRING" #TEST
case "$EXIT" in
	abort|Cancel|"") exit ;;
esac

#make sure that RAMSAVEINTERVAL is an integer only...
[ "$NEWRAMSAVEINTERVAL" = "" ] && NEWRAMSAVEINTERVAL=30 #412
NEWRAMSAVEINTERVAL=`echo -n "$NEWRAMSAVEINTERVAL" | sed -e 's/[^0-9]//g'`
#do not allow too-frequent saves...
[ $NEWRAMSAVEINTERVAL -gt 0 -a $NEWRAMSAVEINTERVAL -lt 5 ] && NEWRAMSAVEINTERVAL=5

#make sure 'ask to save' dialog won't appear at shutdown, if save interval > 0
[ $NEWRAMSAVEINTERVAL -ne 0 ] && NEWASKTOSAVE=false

#w007 make sure that POWERTIMEOUT is integer only...
[ "$NEWPOWERTIMEOUT" = "" ] && NEWPOWERTIMEOUT=0
NEWPOWERTIMEOUT=`echo -n "$NEWPOWERTIMEOUT" | sed -e 's/[^0-9]//g'`
#do not allow too-frequent power-down...
[ $NEWPOWERTIMEOUT -gt 0 -a $NEWPOWERTIMEOUT -lt 5 ] && NEWPOWERTIMEOUT=5

#v403 if major-switch has turned off hotplug support, only show one icon...
NEWHOTPLUGNOISY="false"

touch /etc/eventmanager

# $1=field $2=value
set_em_item() {
	local field=$1 value=$2
	if grep -q "^${field}=" /etc/eventmanager ; then
		sed -i -e "s/^${field}=.*/${field}=${value}/" /etc/eventmanager
	else
		echo "${field}=${value}" >> /etc/eventmanager
	fi
}

set_em_item RAMSAVEINTERVAL ${NEWRAMSAVEINTERVAL}
set_em_item ASKTOSAVE ${NEWASKTOSAVE}
set_em_item POWERTIMEOUT ${NEWPOWERTIMEOUT}
set_em_item HOTPLUGNOISY ${NEWHOTPLUGNOISY}
set_em_item PM13_TRAYICON ${NEWPM13_TRAYICON}

if [ "${NEWPM13_TRAYICON}" = "true" ] ; then
	pm13 trayicon
else
	killall pm13tray 2>/dev/null
fi

if [ "$RAMSAVEINTERVAL" != "${NEWRAMSAVEINTERVAL}" ] ; then
	/etc/init.d/pupmode13 restart
fi

### END ###
