#!/bin/bash
#w__ 2015

case $1 in 
	-cli|cli) CLI=1 ; shift ;;
	-gui|gui) GUI=1 ; shift ;;
	-ip|ip) MYIP=1 ; shift ; shift ;;
esac

export ip="$1"
export cli_stop=""

function ipinfo {
	url='ipinfo.io/json'
	[ "$ip" ] && url="ipinfo.io/${ip}/json"
	while read line ; do
		case $line in \"*)
			line="${line//\"/}"
			read field desc <<< "$line"
			field="${field%:}"
			desc="${desc%,}"
			[ ! "$desc" ] && continue
			echo "$field $desc"
		esac
	done <<< "$(curl "${url}" 2>/dev/null)"
}
export -f ipinfo

###########################################

function ipinfo_cli() {
	[ "$cli_stop" ] && echo
	max=12
	url='ipinfo.io/json'
	while read line ; do
		read field desc <<< "$line"
		fieldl=${#field}
		x=$((max-fieldl))
		echo -n "  $field"
		for ((z=1;z<=x;z++)) ; do echo -n ' ' ; done
		echo ": $desc"
	done <<< "$(ipinfo)"
	if [ "$cli_stop" ] ; then
		echo; echo -n "FINISHED. PRESS ENTER KEY TO CLOSE THIS WINDOW: "
		read zzz
	fi
}
export -f ipinfo_cli

#######################################

function ipinfo_gui() {
	if which yad &>/dev/null ; then
		ok=1
	elif which Xdialog &>/dev/null ; then
		ok=1
	else
		title="ipinfox" ; [ "$ip" ] && title="ipinfox: $ip"
		cli_stop=1
		xterm -title "$title" -e bash -c ipinfo_cli
		exit
	fi
	#---
	url='ipinfo.io/json'
	[ "$ip" ] && url="ipinfo.io/${ip}/json"

	if which Xdialog &>/dev/null ; then
		declare -a fields
		x=0
		while read line ; do
			read -r field desc <<< "$line"
			fields[${x}]="$field" ; let x++
			fields[${x}]="${desc}" ; let x++
			case $field in ip) ip="$desc" ;; esac
		done <<< "$(ipinfo)"
		res=$(Xdialog --title "ipfinfox $ip" --cr-wrap --menu "" 17 76 8 "${fields[@]}" 2>&1)
		echo $res
	#yad
	else
		while read line ; do
			read -r field desc <<< "$line"
			case $field in
				ip)       ip="$desc"       ;;
				hostname) hostname="$desc" ;;
				city)     city="$desc"     ;;
				region)   region="$desc"   ;;
				country)  country="$desc"  ;;
				loc)      loc="$desc"      ;;
				org)      org="$desc"      ;;
			esac
		done <<< "$(ipinfo)"
		
		yad --title="ipfinfox $ip" --no-buttons \
			--width=350 --height=225 --center --list --radio-list \
			--column="field" --column="value" \
			ip "$ip" hostname "$hostname" \
			city "$city" region "$region" country "$country" org "$org" 
	fi
}

###########################################

if [ "$MYIP" ] ; then
	ipinfo | while read line ; do
		read -r field desc <<< "$line"
		case $field in ip)
			echo -n "$desc" > /tmp/ip.external
			echo "$desc"
		esac
	done
	exit
fi

[ "$CLI" ] && { ipinfo_cli ; exit $? ; }
[ "$GUI" ] && { ipinfo_gui ; exit $? ; }

if [ "$DISPLAY" ] ; then
	ipinfo_gui
else
	ipinfo_cli
fi

### END ###