#!/bin/sh
#2014 - safe to use in console mode
#create new files

function help() {
	if [ ! "$1" ]; then
		echo '* Syntax: $0 <type> [filename]'
	else
		echo "* Syntax: $0 $1 [filename]"
	fi
	echo
	exit
}

case $1 in

	script) 
		#[ ! "$2" ] && help script 
		shift
		file='script'
		[ "$1" ] && file="$1"
		echo -e "#!/bin/sh\n" > $file
		chmod +x $file
		echo "Created: $file"
		[ ! "$NOEDIT" ] && geany $file &
		;;

	text)
		#[ ! "$2" ] && help script 
		shift
		file='file.txt'
		[ "$1" ] && file="$1"
		echo "" > $file
		echo "Created: $file"
		[ ! "$NOEDIT" ] && geany $file &
		;;

	portable)
		shift
		dir=new_portable
		[ "$1" ] && dir="$1"
		mkdir -p "$dir"
		mkdir -p "$dir/.config"
		mkdir -p "$dir/bin"
		mkdir -p "$dir/lib"
		cp /usr/sbin/portable-bin "$dir/${dir}"
		chmod +x "$dir/${dir}"
		;;

	desktop)
		shift
		file=$1
		name=${file##*/}
		name=${name%.desktop}
		echo "[Desktop Entry]
Encoding=UTF-8
Type=Application
NoDisplay=true
Name=${name}
Exec=${name}" > ${file}
		[ ! "$NOEDIT" ] && geany ${file} &
		;;

	*) 
		help
		;;
esac

### END ###