#!/bin/sh
# this is meant to be called by a gui, but it's also a cli if you know what you're doing..
# commands are at the end of the script

#==========================================================
#                  HELPER FUNCTIONS
#==========================================================

prompt_to_close_window() {
	# this is exported by a gui app
	if [ $PROMT_TO_CLOSE_WINDOW ] ; then
		echo -en "\nPRESS ENTER TO CLOSE THIS WINDOW"
		read zzz
	fi
}

abort() {
	echo "Abnormal termination.."
	for i in $files2delete ; do rm -rf "$i" ; done
	prompt_to_close_window
	exit 1
}

trap "abort" SIGINT SIGTERM

get_blockdev() {
	[ -z "$1" ] && abort
	if [ -b /dev/${1} ] ; then
		echo /dev/${1}
	elif [ -b /dev/block/${1} ] ; then
		echo /dev/block/${1} #android
	else
		return 1
	fi
	
}

ensure_partition() {
	if [ -z "$1" ] ; then
		echo "Need device name. ex: sda1"
		abort
	elif [ -e /sys/block/${1} ] ; then
		echo "ERROR: $1 is a drive!"
		abort
	fi
}

ensure_drive() {
	if [ -z "$1" ] ; then
		echo "Need device name"
		abort
	elif [ ! -e /sys/block/${1##*/} ] ; then
		echo "ERROR: $1 is not a drive device"
		abort
	fi
}

ensure_no_system_drive() {
	[ -z "$1" ] && abort
	mount -v | grep "^${1}" | grep '/initrd/' && {
		echo "$1 is a system drive	"
		abort
	}
}

ensure_file_exists() {
	if [ -z $1 ] ; then
		abort
	elif [ ! -e ${1} ] ; then
		echo "$1 does not exist.."
		abort
	fi
}

ensure_blockdev() {
	if [ -z $1 ] ; then
		abort
	elif [ ! -b ${1} ] ; then
		echo "$1 is not a block device.."
		abort
	fi
}

ensure_app_exists() {
	if [ -z $1 ] ; then
		abort
	elif ! which $1 &>/dev/null ; then
		echo "$1 is not installed.."
		abort
	fi
}

#==========================================================
#                  FUNCTIONS
#==========================================================

# $1: directory
# $2: distro
# $3: pmedia
copy_g4dos_cd() {
	if [ ! -d "$1" ] ; then
		return 1
	fi
	cp -fv /usr/share/g4dos/pcd/* "$1"/
	if [ "$2" ] ; then #distro
		if [ "$2" = "auto" ] ; then
			. /etc/DISTRO_SPECS
			sed -i "s%#distrodesc#%${DISTRO_NAME} ${DISTRO_VERSION}%" "$1"/menu.lst
		else
			sed -i "s%#distrodesc#%${2}%" "$1"/menu.lst
		fi
	fi
	if [ "$3" ] ; then #pmedia
		sed -i "s|pmedia=cd|pmedia=${3}|" "$1"/menu.lst
	fi
	if [ -f /usr/lib/grub4dos/grldr ] ; then
		cp /usr/lib/grub4dos/grldr "$1"/
	elif [ -f /usr/share/g4dos/grldr ] ; then
		cp /usr/share/g4dos/grldr "$1"/
	fi
}

# $1: drive
write_wee_mbr() {
	XDEV=${1##*/}
	ensure_drive $XDEV
	BLOCKDEV=$(get_blockdev $XDEV)
	WEE_MBR='/usr/share/g4dos/wee.mbr'
	if [ ! -f $WEE_MBR ] ; then
		echo "file not found: $WEE_MBR"
		abort
	fi
	cp ${WEE_MBR} /tmp/wee.mbr
	## Read disk signature and partition table from MBR
	## and write it to wee.mbr:
	dd if=${BLOCKDEV} bs=1 skip=439 count=72 2>/dev/null | \
		dd of=/tmp/wee.mbr bs=1 seek=439 conv=notrunc
	## backup MBR
	dd if=${BLOCKDEV} of=/tmp/${XDEV}.mbr bs=512 count=63
	## Write wee MBR to $MBR_DEV
	echo "Installing bootloader(Wee) on /dev/${XDEV} ..."
	dd if=/tmp/wee.mbr of=${BLOCKDEV}
}

# $1: drive
wipe_drive() {
	XDEV=${1##*/}
	ensure_drive $XDEV
	BLOCKDEV=$(get_blockdev $XDEV) || abort
	echo '#' shred -v -f -n 1 -z ${BLOCKDEV}
	shred -v -f -n 1 -z ${BLOCKDEV} || abort
	prompt_to_close_window
}
# $1: partition
wipe_partition() {
	XDEV=${1##*/}
	ensure_partition $XDEV
	BLOCKDEV=$(get_blockdev $XDEV) || abort
	echo '#' shred -v -f -n 1 -z ${BLOCKDEV}
	shred -v -f -n 1 -z ${BLOCKDEV} || abort
	prompt_to_close_window
}

# [-deep]
# $1: partition
fscheck() {
	for i in $@; do
		[ "$i" = "-deep" ] && { CHKDEEP=1 ; shift ; }
	done
	XDEV=${1##*/}
	BLOCKDEV=$(get_blockdev $XDEV) || abort
	fs=$(probepart ${XDEV} | cut -f 2 -d '|')
	[ "$CHKDEEP" ] && echo "** Intensive check enabled **"
	echo -e "XDEV: $XDEV \n"
	case $fs in
		ext[2-4])
			OPTS='-p'
			[ "$CHKDEEP" ] && OPTS='-p -c' #-c = bad blocks 
			echo '#' e2fsck -v ${OPTS} ${BLOCKDEV}
			e2fsck -v ${OPTS} ${BLOCKDEV} 
			;; 
		vfat)
			OPTS='-p'
			[ "$CHKDEEP" ] && OPTS='-p -t'
			echo '#' fsck.fat -v ${OPTS} ${BLOCKDEV}
			fsck.fat -v ${OPTS} ${BLOCKDEV}
			;;
		ntfs)
			if [ "$CHKDEEP" ] ; then
				echo "No method to thoroughly check NTFS, sorry..."
			else
				echo '#' ntfsfix ${BLOCKDEV}
				ntfsfix ${BLOCKDEV}
			fi
			;;
		exfat)
			if [ "$CHKDEEP" ] ; then
				echo "No method to thoroughly check exfat, sorry..."
			else
				echo '#' exfatfsck ${BLOCKDEV}
				exfatfsck ${BLOCKDEV}
			fi
			;;
		*)
			echo "No method to check $fs filesystem, sorry..."
			;;	
	esac
	prompt_to_close_window
}

# $1: source_drv
# $2: target_drv
clone_drive() {
	source_drv=${1##*/} #basename
	target_drv=${2##*/} #basename
	ensure_drive ${source_drv}
	ensure_drive ${target_drv}
	source_drv=$(get_blockdev $source_drv) || abort
	target_drv=$(get_blockdev $target_drv) || abort
	ensure_no_system_drive ${source_drv}
	ensure_no_system_drive ${target_drv}
	ensure_app_exists ddrescue
	if [ "$source_drv" = "$target_drv" ] ; then
		echo "ERROR: source = destination !"
		abort
	fi
	mapfile=$HOME/rescue.log
	echo "# ddrescue -f -n ${source_drv} ${target_drv} $mapfile"
	ddrescue -f -n ${source_drv} ${target_drv} $mapfile
	echo "# ddrescue -d -D -f -r3 ${source_drv} ${target_drv} $mapfile"
	ddrescue -d -D -f -r3 ${source_drv} ${target_drv} $mapfile
	echo "# ddrescuelog --show-status --binary-prefixes $mapfile"
	ddrescuelog --show-status --binary-prefixes $mapfile
	echo -e "\nexit code: $? (0 = good, otherwise there was an error..)"
	sleep 4
	echo change > /sys/block/${target_drv##*/}/uevent
	if [ $PROMT_TO_CLOSE_WINDOW ] ; then
		which ddrescueview &>/dev/null && ddrescueview $mapfile
	fi
	prompt_to_close_window
}

# $1: devname
# $2: output.backup.drv
backup_drive() {
	source_drv=${1##*/} #basename
	output_file=${2}
	if [ -z "$output_file" ] ; then
		echo "Specify output file. Ex: sdb.backup.drv"
		exit 1
	fi
	case $output_file in
		*.backup.drv) ok=1 ;;
		*) output_file=${output_file}.backup.drv ;;
	esac
	ensure_drive ${source_drv}
	source_drv=$(get_blockdev $source_drv) || abort
	ensure_no_system_drive ${source_drv}
	mapfile=$HOME/backup.log
	echo "# ddrescue -f -n ${source_drv} ${output_file} $mapfile"
	ddrescue -f -n ${source_drv} ${output_file} $mapfile
	echo "ddrescue -d -f -r3 ${source_drv} ${output_file} $mapfile"
	ddrescue -d -f -r3 ${source_drv} ${output_file} $mapfile
	echo "# ddrescuelog --show-status --binary-prefixes $mapfile"
	ddrescuelog --show-status --binary-prefixes $mapfile
	echo -e "\nexit code: $? \n
 0 for a normal exit, otherwise there was an error.."
	if [ $PROMT_TO_CLOSE_WINDOW ] ; then
		which ddrescueview &>/dev/null && ddrescueview $mapfile
	fi
	prompt_to_close_window
}

# $1: input.img[.gz]   [source]
# $2: devname          [target]
restore_drive() {
	BACKUP_FILE="$1"
	target_drv=${2##*/} #basename
	ensure_file_exists "$BACKUP_FILE"
	if [ "$RESTORE_PARTITION" ] ; then
		ensure_partition ${target_drv}
	else
		ensure_drive ${target_drv}
	fi
	target_drv=$(get_blockdev $target_drv) || abort
	ensure_no_system_drive ${target_drv}
	opts="conv=noerror,sync status=progress" #bs=64K 
	case $BACKUP_FILE in *.img|*.img.?z) ok=1 ;;
		*) echo "Backup file must have the '.img' extension"; exit 1;;
	esac
	case $BACKUP_FILE in
		*.gz) echo "# gunzip -d -c "${BACKUP_FILE}" | dd of=${target_drv} $opts"
				gunzip -d -c "${BACKUP_FILE}" | dd of=${target_drv} $opts ;;
		*.bz2)	bzip2 -d -c "${BACKUP_FILE}" | dd of=${target_drv} $opts ;;
		*.xz) echo "# xz -d -c "${BACKUP_FILE}" | dd of=${target_drv} $opts"
				xz -d -c "${BACKUP_FILE}" | dd of=${target_drv} $opts ;;
		*)
			mapfile=$HOME/restorebkp.log
			echo "ddrescue -d -D -f -r3 ${BACKUP_FILE} ${target_drv} $mapfile"
			ddrescue -d -D -f -r3 ${BACKUP_FILE} ${target_drv} $mapfile
			ddrescuelog --show-status --binary-prefixes $mapfile
			echo -e "exit code: $? \n
 0 for a normal exit, otherwise there was an error.."
			sleep 4
			which ddrescueview &>/dev/null && ddrescueview $mapfile &
			;;
	esac
	sleep 4
	echo change > /sys/block/${target_drv##*/}/uevent
	echo -en "\nPRESS ENTER TO CLOSE THIS WINDOW" ; read zzz
}

restore_partition() {
	RESTORE_PARTITION=1
	restore_drive "$@"
}

# [-noerror]
# $1: optilca_drv
# $2: output.iso
cd2iso() {
	ensure_app_exists ddrescue
	for i in $@; do
		[ "$i" = "-noerror" ] && { NO_ERROR_CHECK=1 ; shift ; }
	done
	XDEV=${1##*/}
	OUTFILE="${2}"
	ensure_drive $XDEV
	if [ -z "$2" ] ; then
		echo "Missing output filename (ex: output.iso)"
		exit 1
	fi
	BLOCKDEV=$(get_blockdev $XDEV) || abort
	if [ -z "$XTYPE" ] ; then #not exported by GUI, must get it
		IFS="|" read ZZ XTYPE XSIZE VOLUMEID XMNTSTATUS <<< "$(probepart -hr -extra-info $XDEV)"
		if [ "$XTYPE" = "audiocd" ] ; then
			echo "Can't create ISO from cdaudio.. Try:"
			echo -e "\n	$0 rip-cdaudio $BLOCKDEV \n"
			abort
		fi
	fi
	#-
	[ -z "$VOLUMEID" ] && VOLUMEID=data
	[ -z "$BLOCKSIZE" ] && BLOCKSIZE=2048
	mapfile="/tmp/${VOLUMEID}.log"
	echo "BLOCKSIZE: $BLOCKSIZE"
	echo "VOLUMEID: $VOLUMEID"
	echo
	#-
	if grep -q "^${BLOCKDEV} " /proc/mounts ; then
		umount $BLOCKDEV
		if grep -q "^${BLOCKDEV} " /proc/mounts ; then
			echo "Can't continue: $BLOCKDEV is mounted"
			abort
		fi
	fi
	#-
	if [ $NO_ERROR_CHECK ] ; then
		echo "-- no error check --"
	else
		echo "-- pass 1 --"
	fi
	echo
	#-
	echo '#' ddrescue -n -b${BLOCKSIZE} ${BLOCKDEV} "$OUTFILE" "$mapfile"
	ddrescue -n -b${BLOCKSIZE} ${BLOCKDEV} "$OUTFILE" "$mapfile"
	echo -e "\nExit code: $?"
	#-
	if [ ! $NO_ERROR_CHECK ] ; then
		#2nd pass
		echo -e "\n-- PASS 2 --\n"
		echo '#' ddrescue -d -r5 -b${BLOCKSIZE} ${BLOCKDEV} "$OUTFILE" "$mapfile"
		ddrescue -d -r5 -b${BLOCKSIZE} ${BLOCKDEV} "$OUTFILE" "$mapfile"
		echo -e "\nExit code: $?"
	fi
	#-
	echo '#' ddrescuelog --show-status --binary-prefixes "$mapfile"
	ddrescuelog --show-status --binary-prefixes "$mapfile"
	echo -e "\nexit code: $? (0 = good, otherwise there was an error..)"
	if [ $PROMT_TO_CLOSE_WINDOW ] ; then
		which ddrescueview &>/dev/null && ddrescueview "$mapfile" &
	fi
	echo
	echo -n "Remove $mapfile ? [Y/n]: " ; read answer
	case $answer in
		n|N) notdeleting=1 ;;
		y|Y|"") rm -fv "$mapfile" ;;
	esac
	prompt_to_close_window
}

guess_optical_drive_type() {
	echo aa
}

# $1: dev
# [$2: outdir]
rip_cdaudio() {
	XDEV=/dev/sr0
	[ -d "$2" ] && cd "$2"
	ensure_app_exists cdda2wav
	echo 'Starting.. please wait..'
	files2delete="/tmp/cdrip$$ audio.cddb audio.cdindex"
	mkdir -p /tmp/cdrip$$
	cd /tmp/cdrip$$
	cdinfo=$(cdda2wav dev=$XDEV -info-only -cddb=1 -cuefile 2>&1) #-cddb=1
	retval=$?
	if [ $retval -ne 0 ] ; then
		echo "$(echo "$cdinfo" | grep cdda2wav)"
		abort
	fi
	#-
	cddbfile="$(sed -e 's|=|="|' -e 's|$|"|' audio.cddb)"
	eval "$cddbfile"
	rm -rf /tmp/cdrip$$
	cd -
	#-
	TITLE=${DTITLE#* /}
	ARTIST=${DTITLE%/ *}
	ripdir="$ARTIST - $TITLE"
	ripdir=${ripdir// /_}
	mkdir -p "$ripdir"
	cd "$ripdir"
	echo $PWD
	#-
	cdda2wav cddb=1 speed=4 -paranoia -t all -cuefile out-fd=1 dev=$XDEV
	retval=$?
	rm -f audio.cddb audio.cdindex
	echo -en "\nexit code: $retval \n"
	if [ $retval -eq 0 ] ; then
		sed -i -e '3d' audio.cue
		sed -i -e "2a REM DATE $DYEAR" -e "2a REM GENRE $DGENRE" -e "2a REM DISCID $DISCID" audio.cue
		sed -i -e "1a REM The values below are for reference only, edit as needed.." audio.cue
		if flac audio.wav ; then
			rm audio.wav
			sed -i 's|audio.wav|audio.flac|' audio.cue
		fi
	fi
	unix2dos audio.cue
	[ $PROMT_TO_CLOSE_WINDOW ] && defaultfilemanager
	prompt_to_close_window
}

checkiso() {
	#isoinfo, isodebug, isovfy are from cdrtools package
	ensure_app_exists isoinfo
	ensure_file_exists "$@"
	file "$@"
	echo ==============================================================
	isoinfo -debug -d -i "$@"
	echo ==============================================================
	isodebug "$@"
	echo ==============================================================
	isovfy "$@"
}

# $1: drive
get_dvd_subtitle_list() {
	ensure_app_exists mplayer
	XDEV=$1
	ensure_drive $XDEV
	LANG=C mplayer -frames 0 dvd:// -dvd-device $XDEV 2>&1 | \
		grep sid | grep language | \
		sed -e 's/.*):// ; s/language:// ; s/  / /g ; s/^ // ; s/ $// ; /^$/d'
}
# $1: drive
# $2: text file with subtitles to rip
rip_dvd_subtitles() {
	ensure_app_exists mencoder
	# apps must call get_dvd_subtitle_list() first
	XDEV=$1
	SUBTLIST=$2
	[ -z $OUTFILE ] && OUTFILE=subtitles
	[ -z $INDIVIDUAL ] && INDIVIDUAL=TRUE
	ensure_drive $XDEV
	if [ ! -f "$SUBTLIST" ] ; then
		echo "You must specify a text file with subtitles list"
		exit 1
	fi
	files2delete="$SUBTLIST"
	#-
	if [ "$INDIVIDUAL" != 'TRUE' ] ; then
		rm -f "${OUTFILE}.idx" "${OUTFILE}.sub"
	fi
	index=0
	while read sid id ; do #sid = subtitile id
		echo ${sid} - ${id}
		sleep 2
		VOBOUT="${OUTFILE}"
		VINDEX="$index"
		if [ "$INDIVIDUAL" = 'TRUE' ] ; then
			VOBOUT="${OUTFILE}.${id}"
			VINDEX='0'
			rm -f ${OUTFILE}.${id}.*
		fi
		echo '#' mencoder -o /dev/null ${XDEV} -nosound -ovc copy -vobsubout "${VOBOUT}" -vobsuboutindex ${VINDEX} -vobsuboutid $id -sid $sid
		sleep 2
		mencoder -o /dev/null ${XDEV} -nosound -ovc copy \
			-vobsubout "${VOBOUT}" \
			-vobsuboutindex ${VINDEX} \
			-vobsuboutid ${id} -sid ${sid}
		let index++
	done < $SUBTLIST
	rm -f $SUBTLIST
	prompt_to_close_window
}

#==========================================================
#                  MAIN
#==========================================================

case $1 in
	copy-g4dos-cd)     shift ; copy_g4dos_cd $@  ;; # directory distro pmedia
	write-wee-mbr)     shift ; write_wee_mbr $@  ;; # drv
	wipe-partition)    shift ; wipe_partition $@ ;; # part
	wipe-drive)        shift ; wipe_drive $@     ;; # drv
	fscheck)           shift ; fscheck $@        ;; # [-deep] part
	clone-drive)       shift ; clone_drive $@    ;; # drv1 drv2
	backup-drive)      shift ; backup_drive $@   ;; # drv drv.img
	restore-drive)     shift ; restore_drive $@  ;; # drv.img drv
	restore_partition) shift ; restore_partition $@  ;; # drv.img drv
	cd2iso)            shift ; cd2iso "$@"       ;; # [-noerror] optical_drv output.iso
	rip-cdaudio)       shift ; rip_cdaudio "$@"  ;; # drv [outdir]
	checkiso)          shift ; checkiso "$@"     ;; # file.iso
	get-dvd-subtitle-list) shift ; get_dvd_subtitle_list $@ ;; # (1) drv 
	rip-dvd-subtitles) shift ; rip_dvd_subtitles $@ ;;         # (2) drv subtitles.list
	"") empty_str=1 ;;
	*) echo "command not recognized: $1" ; abort ;;
esac

### EOF ###