v=2.10.1

N=Freenode
E=UTF-8 (Unicode)
F=19
D=0
S=irc.freenode.net/6667

N=Immortal-Anime
E=UTF-8 (Unicode)
F=19
D=0
S=irc.immortal-anime.net/6667

N=Rizon
E=UTF-8 (Unicode)
F=19
D=0
S=irc.rizon.net/6667

N=Undernet
E=IRC (Latin/Unicode Hybrid)
F=19
D=0
S=irc.undernet.org/6667

