#====================================================
#                  misc config
#====================================================
# target arch: default, x86, x86_64, arm, aarch64
#TARGET_ARCH=
# make flags, you may leave this blank or add -j2 -j4 etc
MKFLG=
# yes/no, optimize for size?
OPTIMIZE_FOR_SIZE=yes

#====================================================
#          apps/pgks to compile automatically
#====================================================
#PACKAGES='
#busybox_static
#cryptsetup_static
#dialog_static
#dosfstools_static
#e2fsprogs_static
#f2fs-tools_static
#exfat-utils_static fuse-exfat_static
#mp_static
#ntfs-3g_static
#'
