#====================================================
#       initrd_progs (./build.sh tarball)
#====================================================
# binaries to produce the initrd_progs-date.tar.xz file

# pkg:binary1
INITRD_PROGS='
#busybox_static:busybox
##cryptsetup_static:cryptsetup
##dialog_static:dialog
dosfstools_static:fsck.fat
#e2fsprogs_static:defrag.f2fs fsck.f2fs resize.f2fs
#f2fs-tools_static:e2fsck resize2fs
#exfat-utils_static:exfatfsck
#fuse-exfat_static:mount.exfat-fuse
##mp_static:mp
#ntfs-3g_static:ntfs-3g
'
